export const INPUT_CHANGE = 'INPUT_CHANGE';
export const ADD_TO_LIST = 'ADD_TO_LIST';
export const DELETE_FROM_LIST = 'DELETE_FROM_LIST';
export const ADD_TO_DONE = 'ADD_TO_DONE';
export const DELETE_FROM_DONE = 'DELETE_FROM_DONE';

export const UPDATE_INITIAL_STATE = 'UPDATE_INITIAL_STATE';
